version: '3'
services:
  web:
      container_name: fundacion
      image: hitalos/laravel:7.4
      ports:
          - 80:80
          - 3306:3306
      volumes:
          - ./:/var/www
      networks:
        - app-network

  # scheduler:
  #   container_name: scheduler
  #   build:
  #     context: ./scheduler
  #   environment:
  #     CONTAINER_ROLE: "scheduler" 
  #   ports:
  #     - 443:443
  #   volumes:
  #       - ./:/var/www
  #   networks:
  #     - app-network
  scheduler:
    container_name: scheduler
    image: hitalos/laravel:7.4
    command: sh scheduler.sh
    # environment:
      # CONTAINER_ROLE: "scheduler" 
    ports:
      - 443:443
    volumes:
        - ./:/var/www
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
